name: linn-jupyter-site-template-deploy
on:
  push:
    branches: # listen on which branch(s)
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:  
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if git submodules were used, uncomment next line
          # submodules: true

      - name: Install nbconvert
        run: pip3 install nbconvert jupyter_contrib_nbextensions
      
      - name: Downgrade MarkupSafe
        run: pip3 install MarkupSafe==2.0.0 --force-reinstall
      
      - name: Convert ipynb to markdown of root
        run: jupyter nbconvert *.ipynb --to markdown
        # it would throw an error if no files are matched, but that's ok
        continue-on-error: true
      
      - name: Ignore Error
        run: true
      
      - name: Convert ipynb to markdown of subfolders
        run: jupyter nbconvert **/*.ipynb --to markdown
        # it would throw an error if no files are matched, but that's ok
        continue-on-error: true
      
      - name: Ignore Error
        run: true

        # this book used parent references(../), docsify has problem deal with it
        # so handcraft evaluate those references and replace them
        # only .md and .ipynb will be checked
      - name: Fix Relative References
        run: python3 fix_relative_references.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # the branch to deploy on
          branch: gh-pages
          folder: .

